driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://192.168.56.10:3306/user?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
user=root
pwd=root
usingDB=mysql
srcPath=D:\\code\\java\\orm\\ORM\\src
poPackage=sorm.po
queryClass=sorm.core.MysqlQuery
poolMinSize=10
poolMaxSize=100
